# Generated by Django 2.2.14 on 2020-07-26 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='prueba',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 12, 59, 48, 143337)),
        ),
    ]
